name: Deploy Service to Render

on:
  push:
    branches:
      - main  # Kích hoạt khi có commit được đẩy lên nhánh main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-app:latest .

      # Step 5: Push Docker image lên Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-app:latest

  deploy-to-render:
    needs: docker-build-push  # Đảm bảo job này chỉ chạy sau khi build và push Docker image hoàn tất
    runs-on: ubuntu-latest

    steps:
      # Step 6: Đăng nhập vào Render và deploy service
      - name: Log in to Render
        run: |
          echo ${{ secrets.RENDER_API_KEY }} | curl -X POST https://api.render.com/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "identity-service"}'

      # Step 7: Deploy Docker image lên Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/services/identity-service/deployments \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"image": "${{ secrets.DOCKER_USERNAME }}/identity-app:latest"}'
