name: Deploy Identity Service to Render with Docker

on:
  push:
    branches:
      - main # Nhánh chính mà bạn muốn theo dõi để triển khai

jobs:
  docker-build-push:
    runs-on: ubuntu-latest # Chạy trên môi trường Ubuntu mới nhất

    steps:
      # Bước 1: Kiểm tra mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3 # Sử dụng action để kiểm tra mã nguồn từ nhánh chính

      # Bước 2: Thiết lập Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Thiết lập Docker Buildx để xây dựng hình ảnh Docker

      # Bước 3: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Đăng nhập vào Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Tên người dùng Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }} # Mật khẩu Docker Hub

      # Bước 4: Xây dựng image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-app:latest .

      # Bước 5: Đẩy image Docker lên Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-app:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      # Bước 6: Đăng nhập vào Render
      - name: Log in to Render
        run: |
          echo ${{ secrets.RENDER_API_KEY }} | curl -X POST https://api.render.com/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "identity-service"}'

      # Bước 7: Triển khai ứng dụng lên Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/services/identity-service/deployments \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"image": "${{ secrets.DOCKER_USERNAME }}/identity-app:latest"}'